# 应用基本信息
info:
  app:
    name: ArticlePlatform
    description: 文章标准平台
    version: 0.0.1-SNAPSHOT

# 服务端口配置
server:
  port: 8180

# log打印配置
logging:
  level:
    root: INFO
    # DEBUG 可以打印请求路径,事务,返回的view等
    org.springframework: INFO
    # DEBUG 可以打印Mybatis的sql
    com.xiaobai: DEBUG

# mybatis配置
mybatis:
  # mapperLocations中的classpath指的路径是: src/main/resources
  mapper-locations: classpath:com/xiaobai/mapper/*.xml

# mybatis 分页工具配置
pagehelper:
  # 分页插件方言选择
  helperDialect: mysql
  # 合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# spring相关配置
spring:
  profiles:
    # 本配置文件适用于本机开发环境
    active: local
  # 国际化i18n MessageSource配置
  messages:
    basename: i18n/ResultCode
    cache-duration: 3600s
  # mysql数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/bb_dish?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  # redis配置
#  redis:
#    database: 0
#    host: 140.143.97.102
#    password: pWTYnFuGeS7kEvST
#    timeout: 2000ms

# JWT token认证配置
jwt:
  secretKey: 7b613a6a0ca011e9ab14d663bd873d937b613a6a0ca011e9ab14d663bd873d93
  urlPatterns: /**
  excludedUrls: /,/csrf,/error,/webjars/springfox-swagger-ui/**,/swagger-resources/**,/swagger-ui.html,/user/login

